### PR TITLE
Price quotes

### PR DESCRIPTION
**Pull request by alxberardi**

### CODE REVIEW

**Comment by mnoack** [comment]
:+1: (My understanding is booking-app needs to update to avoid breaking, which is fine by me)

**Comment by mnoack** [comment]
By that I mean if we just update the client it will break, so we should update the caller in booking-app :)

**Comment by alxberardi** [comment]
Yes @mnoack , it is a wanted behaviour and I'm preparing a PR in booking app.

**Comment by alvinypyim** [comment]
:+1:

**Pull request merged**
