### PR TITLE
Tt 608 update qt client to pass the date

### PR DESCRIPTION
**Pull request by jackmcpickle**

### CODE REVIEW

**Comment by alxberardi** [comment]
Unfortunately Travis is unhappy. I'll investigate.

**Comment by alxberardi** [comment]
Travis issues seem to be gem related. Investigating further.

**Comment by alxberardi** [comment]
👍

**Comment by mnoack** [comment]
2.2.2 is the last gem release, I think this all goes under 2.3 really, because the already existing breaking change from 2.3 has clearly not been deployed (if it was done via SHA its' still fine because it's running on bleeding edge like a fool :))

**Comment by alxberardi** [comment]
Fools! Ok, I'll revert to 2.3, but then it should be 2.3.0, as the date support is not a bugfix.

**Comment by alxberardi** [comment]
Done @mnoack

**Comment by mnoack** [comment]
:+1:

**Pull request merged**
